image: node:16.17.1

pipelines:
  custom:
    publish-use-cases:
      - variables:
          - name: USE_CASE_HASH
      - step:
          image: amazon/aws-cli
          name: Fetch use cases
          script:
            ## fetch use cases from s3
            - aws s3 cp s3://cloud-v3-data/useCases/useCases-${USE_CASE_HASH}.json ./useCases/http.json
            ## commit the result
            - git commit -am "Update use cases"
            - git push

  pull-requests:
    "**":
      - step:
          name: Install dependencies and build
          caches:
            - node
          script:
            - npm ci
            - npm rum lint
  branches:
    master:
      - step:
          name: Build and publish to NPM
          caches:
            - node
          script:
            - npm ci
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN
    dev:
      - step:
          name: Build and publish to NPM
          caches:
            - node
          script:
            - npm ci
            - npm version prerelease --preid=beta -m "Upgrade to %s [skip ci]"
            - git push && git push --tags
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN
                EXTRA_ARGS: --tag next

    v1:
      - step:
          name: Build and publish to NPM
          caches:
            - node
          script:
            - npm ci
            - npm version prerelease --preid=beta -m "Upgrade to %s [skip ci]"
            - git push && git push --tags
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN
                EXTRA_ARGS: --tag next-v1
