image: node:16.13

pipelines:
  pull-requests:
    "**":
      - step:
          name: Install dependencies and build
          caches:
            - node
          script:
            - npm install
            - npm version prerelease --preid=alpha -m "Upgrade to %s [skip ci]"
            - git push && git push --tags
            - pipe: atlassian/npm-publish:0.2.6
              variables:
                NPM_TOKEN: $NPM_TOKEN
  branches:
    master:
      - step:
          name: Build and publish to NPM
          caches:
            - node
          script:
            - npm install
            - pipe: atlassian/npm-publish:0.2.6
              variables:
                NPM_TOKEN: $NPM_TOKEN
    dev:
      - step:
          name: Build and publish to NPM
          caches:
            - node
          script:
            - npm install
            - npm version prerelease --preid=beta -m "Upgrade to %s [skip ci]"
            - git push && git push --tags
            - pipe: atlassian/npm-publish:0.2.6
              variables:
                NPM_TOKEN: $NPM_TOKEN
