image: node:16.17.1

definitions:
  install-aws-cli: &install-aws-cli |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    ./aws/install

pipelines:
  custom:
    release:
      - variables:
          - name: USE_CASE_HASH
          - name: PACKAGE_VERSION
      - step:
          image: atlassian/default-image:3
          name: Fetch use cases
          script:
            - *install-aws-cli
            ## fetch use cases from s3
            - aws s3 cp s3://cloud-v3-data/useCases/useCases-${USE_CASE_HASH}.json ./src/useCases/http.json
            ## commit the result
            - git commit -am "Update use cases to hash ${USE_CASE_HASH}"
            - npm version $PACKAGE_VERSION -m "Upgrade to %s"
            - git push && git push --tags

  tags:
    # semver tags
    "v*":
      - step:
          name: Build and publish to NPM
          caches:
            - node
          script:
            - npm ci
            - npm run build
            - npm run lint
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN

  pull-requests:
    "**":
      - step:
          name: Install dependencies and build
          caches:
            - node
          script:
            - npm ci
            - npm run build
            - npm run lint
