image: node:16.17.1

pipelines:
  pull-requests:
    "**":
      - step:
          name: Install dependencies and build
          caches:
            - node
          script:
            - npm install
  branches:
    master:
      - step:
          name: Build and publish to NPM
          caches:
            - node
          script:
            - npm install
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN
    dev:
      - step:
          name: Build and publish to NPM
          caches:
            - node
          script:
            - npm install
            - npm version prerelease --preid=beta -m "Upgrade to %s [skip ci]"
            - git push && git push --tags
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN
                EXTRA_ARGS: --tag next

    v1:
      - step:
          name: Build and publish to NPM
          caches:
            - node
          script:
            - npm install
            - npm version prerelease --preid=beta -m "Upgrade to %s [skip ci]"
            - git push && git push --tags
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN
                EXTRA_ARGS: --tag next-v1
