// This file is auto-generated. Do not edit this file manually.
<<<<<<< HEAD
// Generated on: 2025-04-15T21:03:15.012Z
=======
// Generated on: 2025-04-21T14:11:32.544Z
>>>>>>> 572c05979731730b63612ea49250cd092149d903

export * from "./checkInReservation";
export * from "./checkOutReservation";
export * from "./command";
export * from "./createImageUploadEndpoint";
export * from "./createShortLink";
export * from "./getCategories";
export * from "./getMobileKey";
export * from "./getProducts";
export * from "./getReservationSpaceCategoryAvailabilities";
export * from "./getReservations";
export * from "./getRooms";
export * from "./getUsers";
export * from "./ocrDocument";
export * from "./sellProducts";
export * from "./sendEmail";
export * from "./sendSMS";
export * from "./setAlarm";
export * from "./setCourtesy";
export * from "./setDimmer";
export * from "./setLock";
export * from "./setMedia";
export * from "./setScene";
export * from "./setSwitch";
export * from "./setThermostat";
export * from "./setWindowCovering";
export * from "./updateReservation";
export * from "./updateUser";
export * from "./uploadImage";