// This file is auto-generated. Do not edit this file manually.
// Generated on: 2025-01-04T15:44:02.143Z

import { CheckInReservation } from "./checkInReservation";
import { CheckOutReservation } from "./checkOutReservation";
import { Command } from "./command";
import { CreateImageUploadEndpoint } from "./createImageUploadEndpoint";
import { CreateShortLink } from "./createShortLink";
import { GetCategories } from "./getCategories";
import { GetMobileKey } from "./getMobileKey";
import { GetProducts } from "./getProducts";
import { GetReservationSpaceCategoryAvailabilities } from "./getReservationSpaceCategoryAvailabilities";
import { GetReservations } from "./getReservations";
import { GetRooms } from "./getRooms";
import { GetUsers } from "./getUsers";
import { OCRDocument } from "./ocrDocument";
import { SellProducts } from "./sellProducts";
import { SendEmail } from "./sendEmail";
import { SendSMS } from "./sendSMS";
import { SetAlarm } from "./setAlarm";
import { SetCourtesy } from "./setCourtesy";
import { SetDimmer } from "./setDimmer";
import { SetLock } from "./setLock";
import { SetMedia } from "./setMedia";
import { SetScene } from "./setScene";
import { SetSwitch } from "./setSwitch";
import { SetThermostat } from "./setThermostat";
import { SetWindowCovering } from "./setWindowCovering";
import { UpdateReservation } from "./updateReservation";
import { UpdateUser } from "./updateUser";
import { UploadImage } from "./uploadImage";

// Namespace export
export const Commands = {
  CheckInReservation,
  CheckOutReservation,
  Command,
  CreateImageUploadEndpoint,
  CreateShortLink,
  GetCategories,
  GetMobileKey,
  GetProducts,
  GetReservationSpaceCategoryAvailabilities,
  GetReservations,
  GetRooms,
  GetUsers,
  OCRDocument,
  SellProducts,
  SendEmail,
  SendSMS,
  SetAlarm,
  SetCourtesy,
  SetDimmer,
  SetLock,
  SetMedia,
  SetScene,
  SetSwitch,
  SetThermostat,
  SetWindowCovering,
  UpdateReservation,
  UpdateUser,
  UploadImage,
};
