/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Date =
  | string
  | {
      [k: string]: unknown;
    };

export interface Category {
  id?: string;
  type: string;
  name?: string;
  driver?:
    | "aws-kinesis"
    | "butler"
    | "crestron"
    | "dmp"
    | "dormakaba"
    | "dsc"
    | "ecobee"
    | "igor"
    | "inncom"
    | "kohost-k7"
    | "kohost-pms"
    | "lg"
    | "lirc"
    | "mews"
    | "mht"
    | "paxton"
    | "pelican-wireless"
    | "power-shades"
    | "rebrandly"
    | "salto"
    | "salto-irn"
    | "se"
    | "sendgrid"
    | "sonifi"
    | "stay-n-touch"
    | "twilio"
    | "cloudflare-images"
    | "cloudflare-stream"
    | "insperia-privacy";
  description?: string;
  image?: MediaFile;
  rating?: number;
  discriminator: "space" | "product";
  systemId?: string;
  [k: string]: unknown;
}
/**
 * Any media file
 */
export interface MediaFile {
  id?: string;
  type: string;
  name?: string;
  fileHash?: string;
  mimeType?:
    | "image/*"
    | "image/jpeg"
    | "image/png"
    | "image/gif"
    | "image/webp"
    | "image/avif"
    | "image/svg+xml"
    | "application/pdf";
  data?: string;
  url?: string;
  width?: number;
  height?: number;
  /**
   * Size in bytes
   */
  size?: number;
  uploadUrl?: string;
  uploadUrlExpires?: Date;
  createdBy?: string;
  systemId?: string;
}
