/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Credential {
  id?: string;
  type: string;
  driver?:
    | "aws-kinesis"
    | "butler"
    | "crestron"
    | "dmp"
    | "dormakaba"
    | "dsc"
    | "ecobee"
    | "igor"
    | "inncom"
    | "kohost-k7"
    | "kohost-pms"
    | "lg"
    | "lirc"
    | "mews"
    | "mht"
    | "paxton"
    | "pelican-wireless"
    | "power-shades"
    | "rebrandly"
    | "salto"
    | "salto-irn"
    | "se"
    | "sendgrid"
    | "sonifi"
    | "stay-n-touch"
    | "twilio"
    | "cloudflare-images"
    | "cloudflare-stream"
    | "insperia-privacy";
  discriminator?: "verificationCode" | "token" | "mobileKey" | "pin" | "publicKey" | "passkeyChallenge";
  credential: string;
  user?: string;
  organization?: string;
  property?: string;
  deviceId?: string;
  userAgent?: string;
  expires:
    | string
    | {
        [k: string]: unknown;
      }
    | null;
  systemId?: string;
  [k: string]: unknown;
}
