/* tslint:disable */
/* eslint-disable */
/**
 * This file is generated by core-types-ts on behalf of typeconv, DO NOT EDIT.
 * For more information, see:
 *  - {@link https://github.com/grantila/core-types-ts}
 *  - {@link https://github.com/grantila/typeconv}
 */

/** A device router contains instructions on where to route devices based on their organization and driver. */
export interface DeviceRouterSchema {
    id?: string;
    /**
     * @default
     *     deviceRouter
     */
    type?: string;
    driver: string;
    organization: /** Reference (id) to the organization that owns this router */
    string | /** Reference (id) to the organization that owns this router */
    null;
    devices?: {
        [key: string]: any;
    };
    [key: string]: any;
}
