/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A device router contains instructions on where to route devices based on their organization and driver.
 */
export interface DeviceRouter {
  id?: string;
  type?: string;
  driver: string;
  /**
   * Reference (id) to the organization that owns this router
   */
  organization: string | null;
  devices?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
