/* tslint:disable */
/* eslint-disable */
/**
 * This file is generated by core-types-ts on behalf of typeconv, DO NOT EDIT.
 * For more information, see:
 *  - {@link https://github.com/grantila/core-types-ts}
 *  - {@link https://github.com/grantila/typeconv}
 */

export interface EmailMessageSchema {
    id?: string;
    /**
     * @default
     *     emailMessage
     */
    type?: string;
    to: string;
    /** Must be in the format of 'Sender <email@example.com> */
    from: string;
    subject: string;
    status: "queued" | "sending" | "sent" | "deferred" | "delivered" | "undelivered" | "bounced" | "blocked" | "receiving" | "received" | "opened" | "clicked" | "unsubscribed" | "spamReport";
    statusMessage?: string;
    html?: string;
    text?: string;
    driver?: string;
    appData?: {
        [key: string]: any;
    };
    createdAt?: string | {
        [key: string]: any;
    };
    updatedAt?: string | {
        [key: string]: any;
    };
    systemId?: string;
    [key: string]: any;
}
