/** Declaration file generated by dts-gen */

declare function index(...args: any[]): void;


declare namespace index {
    class AMQPClient {
        constructor(...args: any[]);

        assertExchange(...args: any[]): void;

        assertQueue(...args: any[]): void;

        bindExchange(...args: any[]): void;

        bindQueue(...args: any[]): void;

        createChannel(...args: any[]): void;

        createConnection(...args: any[]): void;

        publishToExchange(...args: any[]): void;

        subscribeToQueue(...args: any[]): void;

        static createMessage(...args: any[]): void;

        static exchanges: {
            AppEvents: {
                name: string;
                options: {
                    durable: boolean;
                };
                type: string;
            };
            Commands: {
                name: string;
                options: {
                    durable: boolean;
                };
                type: string;
            };
            Direct: {
                name: string;
                options: {
                    durable: boolean;
                };
                type: string;
            };
            DriverEvents: {
                name: string;
                options: {
                    durable: boolean;
                };
                type: string;
            };
            Replies: {
                name: string;
                options: {
                    durable: boolean;
                };
                type: string;
            };
            dlx: {
                name: string;
                type: string;
            };
        };

        static generateCorrelationId(...args: any[]): void;

        static getMessage(...args: any[]): void;

        static isFatalError(...args: any[]): void;

        static parseError(...args: any[]): void;

        static parseMessage(...args: any[]): void;

        static validateMessage(...args: any[]): void;

    }

    class Client {
        constructor(...args: any[]);

        static addAbortListener(signal: any, listener: any): any;

        static captureRejectionSymbol: any;

        static captureRejections: boolean;

        static defaultMaxListeners: number;

        static defs: {
            apiKeyHeader: string;
            organizationHeader: string;
            propertyHeader: string;
        };

        static errorMonitor: any;

        static getEventListeners(emitterOrTarget: any, type: any): any;

        static getMaxListeners(emitterOrTarget: any): any;

        static init(opts: any): void;

        static kMaxEventTargetListeners: any;

        static kMaxEventTargetListenersWarned: any;

        static listenerCount(emitter: any, type: any): any;

        static on(emitter: any, event: any, options: any): any;

        static once(emitter: any, name: any, options: any): any;

        static setMaxListeners(n: any, eventTargets: any): void;

        static usingDomains: boolean;

    }

    class SocketIoClient {
        constructor(...args: any[]);

        connect(...args: any[]): void;

        destroy(...args: any[]): void;

        disconnect(...args: any[]): void;

        reconnect(...args: any[]): void;

        send(...args: any[]): void;

        subscribe(...args: any[]): void;

        unsubscribe(...args: any[]): void;

        static addAbortListener(signal: any, listener: any): any;

        static captureRejectionSymbol: any;

        static captureRejections: boolean;

        static defaultMaxListeners: number;

        static errorMonitor: any;

        static getEventListeners(emitterOrTarget: any, type: any): any;

        static getMaxListeners(emitterOrTarget: any): any;

        static init(opts: any): void;

        static kMaxEventTargetListeners: any;

        static kMaxEventTargetListenersWarned: any;

        static listenerCount(emitter: any, type: any): any;

        static on(emitter: any, event: any, options: any): any;

        static once(emitter: any, name: any, options: any): any;

        static setMaxListeners(n: any, eventTargets: any): void;

        static usingDomains: boolean;

    }

    const defs: {
        deviceTypes: string[];
        formalDeviceTypes: string[];
        http: {
            apiKeyHeader: string;
            organizationHeader: string;
            propertyHeader: string;
        };
    };

    namespace AMQPClient {
        class Message {
            constructor(...args: any[]);

            build(...args: any[]): void;

            to(...args: any[]): void;

            withContext(...args: any[]): void;

            withCorrelationId(...args: any[]): void;

            withHeaders(...args: any[]): void;

            withReplyTo(...args: any[]): void;

            withRoutingKey(...args: any[]): void;

            withType(...args: any[]): void;

        }

    }

    namespace Client {
        class EventEmitter {
            constructor(opts: any);

            addListener(type: any, listener: any): any;

            emit(type: any, args: any): any;

            eventNames(): any;

            getMaxListeners(): any;

            listenerCount(type: any, listener: any): any;

            listeners(type: any): any;

            off(type: any, listener: any): any;

            on(type: any, listener: any): any;

            once(type: any, listener: any): any;

            prependListener(type: any, listener: any): any;

            prependOnceListener(type: any, listener: any): any;

            rawListeners(type: any): any;

            removeAllListeners(type: any, ...args: any[]): any;

            removeListener(type: any, listener: any): any;

            setMaxListeners(n: any): any;

            static EventEmitter: any;

            static addAbortListener(signal: any, listener: any): any;

            static captureRejectionSymbol: any;

            static captureRejections: boolean;

            static defaultMaxListeners: number;

            static errorMonitor: any;

            static getEventListeners(emitterOrTarget: any, type: any): any;

            static getMaxListeners(emitterOrTarget: any): any;

            static init(opts: any): void;

            static kMaxEventTargetListeners: any;

            static kMaxEventTargetListenersWarned: any;

            static listenerCount(emitter: any, type: any): any;

            static on(emitter: any, event: any, options: any): any;

            static once(emitter: any, name: any, options: any): any;

            static setMaxListeners(n: any, eventTargets: any): void;

            static usingDomains: boolean;

        }

        class EventEmitterAsyncResource {
            constructor(...args: any[]);

            emit(...args: any[]): void;

            emitDestroy(...args: any[]): void;

            static EventEmitterAsyncResource: any;

            static addAbortListener(signal: any, listener: any): any;

            static captureRejectionSymbol: any;

            static captureRejections: boolean;

            static defaultMaxListeners: number;

            static errorMonitor: any;

            static getEventListeners(emitterOrTarget: any, type: any): any;

            static getMaxListeners(emitterOrTarget: any): any;

            static init(opts: any): void;

            static kMaxEventTargetListeners: any;

            static kMaxEventTargetListenersWarned: any;

            static listenerCount(emitter: any, type: any): any;

            static on(emitter: any, event: any, options: any): any;

            static once(emitter: any, name: any, options: any): any;

            static setMaxListeners(n: any, eventTargets: any): void;

            static usingDomains: boolean;

        }

        namespace EventEmitter {
            class EventEmitterAsyncResource {
                constructor(...args: any[]);

                emit(...args: any[]): void;

                emitDestroy(...args: any[]): void;

                static EventEmitter: any;

                static EventEmitterAsyncResource: any;

                static addAbortListener(signal: any, listener: any): any;

                static captureRejectionSymbol: any;

                static captureRejections: boolean;

                static defaultMaxListeners: number;

                static errorMonitor: any;

                static getEventListeners(emitterOrTarget: any, type: any): any;

                static getMaxListeners(emitterOrTarget: any): any;

                static init(opts: any): void;

                static kMaxEventTargetListeners: any;

                static kMaxEventTargetListenersWarned: any;

                static listenerCount(emitter: any, type: any): any;

                static on(emitter: any, event: any, options: any): any;

                static once(emitter: any, name: any, options: any): any;

                static setMaxListeners(n: any, eventTargets: any): void;

                static usingDomains: boolean;

            }

        }

        namespace EventEmitterAsyncResource {
            class EventEmitter {
                constructor(opts: any);

                addListener(type: any, listener: any): any;

                emit(type: any, args: any): any;

                eventNames(): any;

                getMaxListeners(): any;

                listenerCount(type: any, listener: any): any;

                listeners(type: any): any;

                off(type: any, listener: any): any;

                on(type: any, listener: any): any;

                once(type: any, listener: any): any;

                prependListener(type: any, listener: any): any;

                prependOnceListener(type: any, listener: any): any;

                rawListeners(type: any): any;

                removeAllListeners(type: any, ...args: any[]): any;

                removeListener(type: any, listener: any): any;

                setMaxListeners(n: any): any;

                static EventEmitter: any;

                static EventEmitterAsyncResource: any;

                static addAbortListener(signal: any, listener: any): any;

                static captureRejectionSymbol: any;

                static captureRejections: boolean;

                static defaultMaxListeners: number;

                static errorMonitor: any;

                static getEventListeners(emitterOrTarget: any, type: any): any;

                static getMaxListeners(emitterOrTarget: any): any;

                static init(opts: any): void;

                static kMaxEventTargetListeners: any;

                static kMaxEventTargetListenersWarned: any;

                static listenerCount(emitter: any, type: any): any;

                static on(emitter: any, event: any, options: any): any;

                static once(emitter: any, name: any, options: any): any;

                static setMaxListeners(n: any, eventTargets: any): void;

                static usingDomains: boolean;

            }

        }

    }

    namespace Commands {
        class CheckInReservationCommand {
            constructor(...args: any[]);

        }

        class CheckOutReservationCommand {
            constructor(...args: any[]);

        }

        class CreateImageUploadEndpointCommand {
            constructor(...args: any[]);

        }

        class CreateShortLinkCommand {
            constructor(...args: any[]);

        }

        class DiscoverCategoriesCommand {
            constructor(...args: any[]);

        }

        class DiscoverReservationSpaceCategoryAvailabilitiesCommand {
            constructor(...args: any[]);

        }

        class DiscoverReservationsCommand {
            constructor(...args: any[]);

        }

        class DiscoverRoomsCommand {
            constructor(...args: any[]);

        }

        class DiscoverUsersCommand {
            constructor(...args: any[]);

        }

        class GetMobileKeyCommand {
            constructor(...args: any[]);

        }

        class GetProductsCommand {
            constructor(...args: any[]);

        }

        class OCRDocumentCommand {
            constructor(...args: any[]);

        }

        class SellProductsCommand {
            constructor(...args: any[]);

        }

        class SendEmailCommand {
            constructor(...args: any[]);

        }

        class SendSMSCommand {
            constructor(...args: any[]);

        }

        class SetAlarmCommand {
            constructor(...args: any[]);

        }

        class SetCourtesyCommand {
            constructor(...args: any[]);

        }

        class SetDimmerCommand {
            constructor(...args: any[]);

        }

        class SetLockCommand {
            constructor(...args: any[]);

        }

        class SetMediaCommand {
            constructor(...args: any[]);

        }

        class SetSceneCommand {
            constructor(...args: any[]);

        }

        class SetSwitchCommand {
            constructor(...args: any[]);

        }

        class SetThermostatCommand {
            constructor(...args: any[]);

        }

        class SetWindowCoveringCommand {
            constructor(...args: any[]);

        }

        class UpdateReservationCommand {
            constructor(...args: any[]);

        }

        class UpdateUserCommand {
            constructor(...args: any[]);

        }

        class UploadImageCommand {
            constructor(...args: any[]);

        }

    }

    namespace Errors {
        function AppError(...args: any[]): void;

        function AuthenticationError(...args: any[]): void;

        function AuthorizationError(...args: any[]): void;

        function ConflictError(...args: any[]): void;

        function DeviceCommError(...args: any[]): void;

        function LoginError(...args: any[]): void;

        function NotFoundError(...args: any[]): void;

        function RequestError(...args: any[]): void;

        function SystemCommError(...args: any[]): void;

        function TokenExpiredError(...args: any[]): void;

        function UnprocessableRequestError(...args: any[]): void;

        function ValidationError(...args: any[]): void;

        namespace AppError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace AuthenticationError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace AuthorizationError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace ConflictError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace DeviceCommError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace LoginError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace NotFoundError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace RequestError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace SystemCommError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace TokenExpiredError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace UnprocessableRequestError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

        namespace ValidationError {
            const stackTraceLimit: number;

            function captureStackTrace(p0: any, p1: any): any;

        }

    }

    namespace Events {
        class ApplicationInUseEvent {
            constructor(...args: any[]);

        }

        class ApplicationOutOfUseEvent {
            constructor(...args: any[]);

        }

        class EmailEvent {
            constructor(...args: any[]);

        }

        class ReservationCheckInEvent {
            constructor(...args: any[]);

            static entity: string;

        }

        class ReservationCheckOutEvent {
            constructor(...args: any[]);

            static entity: string;

        }

        class SMSEvent {
            constructor(...args: any[]);

        }

        class SceneSetEvent {
            constructor(...args: any[]);

        }

        class ShortLinkCreatedEvent {
            constructor(...args: any[]);

        }

        class SystemAlarmUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemCameraUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemCategoryUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemCourtesyUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemCredentialUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemDimmerUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemEntityDeletedEvent {
            constructor(...args: any[]);

        }

        class SystemGatewayUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemLockUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemMediaSourceUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemMotionSensorUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemOrganizationUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemProductUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemPropertyUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemReservationUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemSceneControllerUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemSpaceUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemSwitchUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemThermostatUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemUserUpdatedEvent {
            constructor(...args: any[]);

        }

        class SystemWindowCoveringUpdatedEvent {
            constructor(...args: any[]);

        }

    }

    namespace Models {
        class Alarm {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Announcement {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Camera {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Category {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Courtesy {
            constructor(...args: any[]);

            static actionProperties: string[];

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Credential {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class DeviceRouter {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Dimmer {
            constructor(...args: any[]);

            static actionProperties: string[];

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class DiscoveredDevice {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class EmailMessage {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class EnergyReport {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class EnergyReportShard {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Entity {
            constructor(...args: any[]);

            toObject(...args: any[]): void;

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: any[];

        }

        class Gateway {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Identification {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Lock {
            constructor(...args: any[]);

            static actionProperties: string[];

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class MediaFile {
            constructor(...args: any[]);

            createImageVariant(...args: any[]): void;

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class MediaSource {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class MotionSensor {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Order {
            constructor(...args: any[]);

            getBalance(...args: any[]): void;

            getDeliveryTotal(...args: any[]): void;

            getFeesTotal(...args: any[]): void;

            getPaymentsTotal(...args: any[]): void;

            getSubTotal(...args: any[]): void;

            getTaxTotal(...args: any[]): void;

            getTotal(...args: any[]): void;

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Organization {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Product {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Property {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Reservation {
            constructor(...args: any[]);

            checkInTime(...args: any[]): void;

            checkOutTime(...args: any[]): void;

            range(...args: any[]): void;

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Room {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static getDevicePath(...args: any[]): void;

            static getDeviceTypeFromPath(...args: any[]): void;

            static validProperties: string[];

        }

        class SMSMessage {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Scene {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static getRoomSceneDeviceData(...args: any[]): void;

            static validProperties: string[];

        }

        class ShortLink {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Space {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Switch {
            constructor(...args: any[]);

            static actionProperties: string[];

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class SystemUser {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

            static validateEmail(...args: any[]): void;

            static validatePhone(...args: any[]): void;

        }

        class Thermostat {
            constructor(...args: any[]);

            toCelsius(...args: any[]): void;

            toFahrenheit(...args: any[]): void;

            static actionProperties: string[];

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class Ticket {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static generateMessageId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class TimeSheet {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static generateTimeEntryId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

        class User {
            constructor(...args: any[]);

            static generateId(...args: any[]): void;

            static generatePassword(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

            static validateEmail(...args: any[]): void;

            static validatePhone(...args: any[]): void;

        }

        class WindowCovering {
            constructor(...args: any[]);

            static actionProperties: string[];

            static generateId(...args: any[]): void;

            static getActionDelta(...args: any[]): void;

            static validProperties: string[];

        }

    }

    namespace SocketIoClient {
        class EventEmitter {
            constructor(opts: any);

            addListener(type: any, listener: any): any;

            emit(type: any, args: any): any;

            eventNames(): any;

            getMaxListeners(): any;

            listenerCount(type: any, listener: any): any;

            listeners(type: any): any;

            off(type: any, listener: any): any;

            on(type: any, listener: any): any;

            once(type: any, listener: any): any;

            prependListener(type: any, listener: any): any;

            prependOnceListener(type: any, listener: any): any;

            rawListeners(type: any): any;

            removeAllListeners(type: any, ...args: any[]): any;

            removeListener(type: any, listener: any): any;

            setMaxListeners(n: any): any;

            static EventEmitter: any;

            static addAbortListener(signal: any, listener: any): any;

            static captureRejectionSymbol: any;

            static captureRejections: boolean;

            static defaultMaxListeners: number;

            static errorMonitor: any;

            static getEventListeners(emitterOrTarget: any, type: any): any;

            static getMaxListeners(emitterOrTarget: any): any;

            static init(opts: any): void;

            static kMaxEventTargetListeners: any;

            static kMaxEventTargetListenersWarned: any;

            static listenerCount(emitter: any, type: any): any;

            static on(emitter: any, event: any, options: any): any;

            static once(emitter: any, name: any, options: any): any;

            static setMaxListeners(n: any, eventTargets: any): void;

            static usingDomains: boolean;

        }

        class EventEmitterAsyncResource {
            constructor(...args: any[]);

            emit(...args: any[]): void;

            emitDestroy(...args: any[]): void;

            static EventEmitterAsyncResource: any;

            static addAbortListener(signal: any, listener: any): any;

            static captureRejectionSymbol: any;

            static captureRejections: boolean;

            static defaultMaxListeners: number;

            static errorMonitor: any;

            static getEventListeners(emitterOrTarget: any, type: any): any;

            static getMaxListeners(emitterOrTarget: any): any;

            static init(opts: any): void;

            static kMaxEventTargetListeners: any;

            static kMaxEventTargetListenersWarned: any;

            static listenerCount(emitter: any, type: any): any;

            static on(emitter: any, event: any, options: any): any;

            static once(emitter: any, name: any, options: any): any;

            static setMaxListeners(n: any, eventTargets: any): void;

            static usingDomains: boolean;

        }

        namespace EventEmitter {
            class EventEmitterAsyncResource {
                constructor(...args: any[]);

                emit(...args: any[]): void;

                emitDestroy(...args: any[]): void;

                static EventEmitter: any;

                static EventEmitterAsyncResource: any;

                static addAbortListener(signal: any, listener: any): any;

                static captureRejectionSymbol: any;

                static captureRejections: boolean;

                static defaultMaxListeners: number;

                static errorMonitor: any;

                static getEventListeners(emitterOrTarget: any, type: any): any;

                static getMaxListeners(emitterOrTarget: any): any;

                static init(opts: any): void;

                static kMaxEventTargetListeners: any;

                static kMaxEventTargetListenersWarned: any;

                static listenerCount(emitter: any, type: any): any;

                static on(emitter: any, event: any, options: any): any;

                static once(emitter: any, name: any, options: any): any;

                static setMaxListeners(n: any, eventTargets: any): void;

                static usingDomains: boolean;

            }

        }

        namespace EventEmitterAsyncResource {
            class EventEmitter {
                constructor(opts: any);

                addListener(type: any, listener: any): any;

                emit(type: any, args: any): any;

                eventNames(): any;

                getMaxListeners(): any;

                listenerCount(type: any, listener: any): any;

                listeners(type: any): any;

                off(type: any, listener: any): any;

                on(type: any, listener: any): any;

                once(type: any, listener: any): any;

                prependListener(type: any, listener: any): any;

                prependOnceListener(type: any, listener: any): any;

                rawListeners(type: any): any;

                removeAllListeners(type: any, ...args: any[]): any;

                removeListener(type: any, listener: any): any;

                setMaxListeners(n: any): any;

                static EventEmitter: any;

                static EventEmitterAsyncResource: any;

                static addAbortListener(signal: any, listener: any): any;

                static captureRejectionSymbol: any;

                static captureRejections: boolean;

                static defaultMaxListeners: number;

                static errorMonitor: any;

                static getEventListeners(emitterOrTarget: any, type: any): any;

                static getMaxListeners(emitterOrTarget: any): any;

                static init(opts: any): void;

                static kMaxEventTargetListeners: any;

                static kMaxEventTargetListenersWarned: any;

                static listenerCount(emitter: any, type: any): any;

                static on(emitter: any, event: any, options: any): any;

                static once(emitter: any, name: any, options: any): any;

                static setMaxListeners(n: any, eventTargets: any): void;

                static usingDomains: boolean;

            }

        }

    }

    namespace utils {
        function errorFactory(errName: any): any;

        function getDeviceTypes(): any;

        function getFormalDeviceType(deviceType: any): any;

        namespace schema {
            function add(schema: any): void;

            function compile(schema: any): any;

        }

    }

}

