/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SupportedNotifications = (
  | "button 1"
  | "button 2"
  | "button 3"
  | "button 4"
  | "button 5"
  | "idle"
  | "powerHasBeedApplied"
  | "acMainsDisconnected"
  | "acMainsReconnected"
  | "replaceBatterySoon"
  | "replaceBatteryNow"
  | "hardwareFailure"
  | "softwareFailure"
  | "hardwareFailureWithCode"
  | "softwareFailureWithCode"
  | "motionDetection"
  | "airFilterNeedsCleaned"
  | "airFilterNeedsReplaced"
  | "smokeDetected"
  | "outsideSafeTemperatureRange"
  | "outsideSafeHumidityRange"
  | "scheduleMaintenance"
)[];
export type Notification = {
  name?:
    | "button 1"
    | "button 2"
    | "button 3"
    | "button 4"
    | "button 5"
    | "idle"
    | "powerHasBeedApplied"
    | "acMainsDisconnected"
    | "acMainsReconnected"
    | "replaceBatterySoon"
    | "replaceBatteryNow"
    | "hardwareFailure"
    | "softwareFailure"
    | "hardwareFailureWithCode"
    | "softwareFailureWithCode"
    | "motionDetection"
    | "airFilterNeedsCleaned"
    | "airFilterNeedsReplaced"
    | "smokeDetected"
    | "outsideSafeTemperatureRange"
    | "outsideSafeHumidityRange"
    | "scheduleMaintenance";
  timestamp?: number;
  description?: string;
  [k: string]: unknown;
} & ({
  name?:
    | "button 1"
    | "button 2"
    | "button 3"
    | "button 4"
    | "button 5"
    | "idle"
    | "powerHasBeedApplied"
    | "acMainsDisconnected"
    | "acMainsReconnected"
    | "replaceBatterySoon"
    | "replaceBatteryNow"
    | "hardwareFailure"
    | "softwareFailure"
    | "hardwareFailureWithCode"
    | "softwareFailureWithCode"
    | "motionDetection"
    | "airFilterNeedsCleaned"
    | "airFilterNeedsReplaced"
    | "smokeDetected"
    | "outsideSafeTemperatureRange"
    | "outsideSafeHumidityRange"
    | "scheduleMaintenance";
  timestamp?: number;
  description?: string;
  [k: string]: unknown;
} | null);

/**
 * Any smart lock
 */
export interface Lock {
  id: string;
  name?: string;
  type:
    | "alarm"
    | "dimmer"
    | "switch"
    | "motionSensor"
    | "windowCovering"
    | "camera"
    | "mediaSource"
    | "thermostat"
    | "lock"
    | "courtesy"
    | "gateway"
    | "tv"
    | "dvr"
    | "appleTv"
    | "discPlayer"
    | "mediaPlayer"
    | "uncontrolledDevice";
  offline?: boolean;
  supportedNotifications?: SupportedNotifications;
  notification?: Notification;
  driver:
    | "aws-kinesis"
    | "butler"
    | "crestron"
    | "dmp"
    | "dormakaba"
    | "dsc"
    | "ecobee"
    | "igor"
    | "inncom"
    | "kohost-k7"
    | "kohost-pms"
    | "lg"
    | "lirc"
    | "mews"
    | "mht"
    | "paxton"
    | "pelican-wireless"
    | "power-shades"
    | "rebrandly"
    | "salto"
    | "salto-irn"
    | "se"
    | "sendgrid"
    | "sonifi"
    | "stay-n-touch"
    | "twilio"
    | "cloudflare-images"
    | "cloudflare-stream"
    | "insperia-privacy";
  state: "locked" | "unlocked" | null;
  /**
   * AutoLock: Lock automatically locks after set time. Normal - Lock needs told to lock or unlock.
   */
  mode?: "normal" | "autoLock" | null;
  batteryLevel?: number;
  systemId?: string;
  watts?: number;
  [k: string]: unknown;
}
