/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Date =
  | string
  | {
      [k: string]: unknown;
    };

/**
 * Any media file
 */
export interface MediaFile {
  id?: string;
  type: string;
  name?: string;
  fileHash?: string;
  mimeType?:
    | "image/*"
    | "image/jpeg"
    | "image/png"
    | "image/gif"
    | "image/webp"
    | "image/avif"
    | "image/svg+xml"
    | "application/pdf";
  data?: string;
  url?: string;
  width?: number;
  height?: number;
  /**
   * Size in bytes
   */
  size?: number;
  uploadUrl?: string;
  uploadUrlExpires?: Date;
  createdBy?: string;
  systemId?: string;
}
