/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Date =
  | string
  | {
      [k: string]: unknown;
    };

/**
 * A purchase order for products or services.
 */
export interface Order {
  id?: string;
  type: string;
  orderNumber?: string;
  status:
    | "draft"
    | "pendingPayment"
    | "processing"
    | "outForDelivery"
    | "completed"
    | "paymentFailed"
    | "cancelled"
    | "refunded";
  /**
   * User id of purchaser
   */
  user?: string;
  date?: Date;
  items?: {
    additionalProperties?: never;
    name: string;
    sku?: string;
    quantity?: number;
    price: number;
    taxClass?: string;
    deliveryClass?: string;
    [k: string]: unknown;
  }[];
  taxes?: {
    additionalProperties?: never;
    name: string;
    class?: string;
    rateType?: "percentage" | "flat";
    rate: number;
    total?: number;
    [k: string]: unknown;
  }[];
  fees?: {
    additionalProperties?: never;
    name: string;
    price: number;
    [k: string]: unknown;
  }[];
  delivery?: {
    additionalProperties?: never;
    name: string;
    class?: string;
    rateType?: "percentage" | "flat";
    rate: number;
    total?: number;
    [k: string]: unknown;
  }[];
  payments?: {
    method?:
      | "folio"
      | "invoice"
      | "amex"
      | "visa"
      | "masterCard"
      | "maestro"
      | "discover"
      | "diners"
      | "jcb"
      | "applePay"
      | "alipay"
      | "chinaUnionPay"
      | "vpay";
    name?: string;
    date?: Date;
    amount?: number;
    transactionReference?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
