/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreatedAt =
  | string
  | {
      [k: string]: unknown;
    };
export type UpdatedAt =
  | string
  | {
      [k: string]: unknown;
    };

/**
 * An organization is a group or entity that subscribes to Kohost software.
 */
export interface Organization {
  id?: string;
  type?: string;
  accountNumber: number | null;
  name: string;
  properties?: string[];
  hostname?: string | null;
  appManifest?: {
    name?: string;
    short_name?: string;
    scope?: string;
    start_url?: string;
    themeColor?: string;
    backgroundColor?: string;
    display?: "fullscreen" | "standalone" | "minimal-ui" | "browser";
    orientation?: "portrait" | "landscape";
    splash?: {
      src?: string;
      type?: string;
      sizes?: string;
      [k: string]: unknown;
    };
    icons?: {
      src?: string;
      sizes?: string;
      type?: string;
      [k: string]: unknown;
    }[];
    logo?: {
      src?: string;
      type?: string;
      sizes?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  credentials?: {
    [k: string]: unknown;
  };
  createdAt?: CreatedAt;
  updatedAt?: UpdatedAt;
  [k: string]: unknown;
}
