/* tslint:disable */
/* eslint-disable */
/**
 * This file is generated by core-types-ts on behalf of typeconv, DO NOT EDIT.
 * For more information, see:
 *  - {@link https://github.com/grantila/core-types-ts}
 *  - {@link https://github.com/grantila/typeconv}
 */

/** An organization is a group or entity that subscribes to Kohost software. */
export interface OrganizationSchema {
    id?: string;
    /**
     * @default
     *     organization
     */
    type?: string;
    accountNumber: number | null;
    name: string;
    properties?: string[];
    hostname?: string | null;
    /**
     * @default
     *     {
     *       "name": "Kohost",
     *       "short_name": "Kohost",
     *       "start_url": "/",
     *       "scope": "/",
     *       "display": "fullscreen",
     *       "orientation": "portrait",
     *       "theme_color": "#1d1f22",
     *       "background_color": "#1d1f22",
     *       "icons": [
     *         {
     *           "src": "https://images.kohost.io/cdn-cgi/imagedelivery/vcVX2aBwdFSYr66spcFKaA/9c85047f-ccba-4b1c-3070-5463fbe93b00/w=512",
     *           "sizes": "512x512",
     *           "type": "image/png"
     *         }
     *       ],
     *       "splash": {
     *         "src": "https://images.kohost.io/cdn-cgi/imagedelivery/vcVX2aBwdFSYr66spcFKaA/034fb112-5326-4d37-373e-d1cc2a4d0400/w=1500",
     *         "sizes": "1500x800",
     *         "type": "image/jpg"
     *       },
     *       "logo": {
     *         "src": "https://images.kohost.io/cdn-cgi/imagedelivery/vcVX2aBwdFSYr66spcFKaA/1e54c54d-3bac-4745-f46f-c2f98036af00/h=75",
     *         "sizes": "300x75",
     *         "type": "image/png"
     *       }
     *     }
     */
    appManifest?: {
        name?: string;
        short_name?: string;
        scope?: string;
        start_url?: string;
        themeColor?: string;
        backgroundColor?: string;
        /**
         * @default
         *     fullscreen
         */
        display?: "fullscreen" | "standalone" | "minimal-ui" | "browser";
        /**
         * @default
         *     portrait
         */
        orientation?: "portrait" | "landscape";
        splash?: {
            src?: string;
            type?: string;
            sizes?: string;
            [key: string]: any;
        };
        icons?: {
            src?: string;
            sizes?: string;
            type?: string;
            [key: string]: any;
        }[];
        logo?: {
            src?: string;
            type?: string;
            sizes?: string;
            [key: string]: any;
        };
        [key: string]: any;
    };
    credentials?: {
        [key: string]: any;
    };
    createdAt?: string | {
        [key: string]: any;
    };
    updatedAt?: string | {
        [key: string]: any;
    };
    [key: string]: any;
}
