/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Revenue = {
  id?: string;
  name?: string;
  date?: string;
  price?: number;
  tax?: number | null;
  [k: string]: unknown;
}[];
export type UpdatedAt =
  | string
  | {
      [k: string]: unknown;
    };

export interface Reservation {
  id?: string;
  driver?:
    | "aws-kinesis"
    | "butler"
    | "crestron"
    | "dmp"
    | "dormakaba"
    | "dsc"
    | "ecobee"
    | "igor"
    | "inncom"
    | "kohost-k7"
    | "kohost-pms"
    | "lg"
    | "lirc"
    | "mews"
    | "mht"
    | "paxton"
    | "pelican-wireless"
    | "power-shades"
    | "rebrandly"
    | "salto"
    | "salto-irn"
    | "se"
    | "sendgrid"
    | "sonifi"
    | "stay-n-touch"
    | "twilio"
    | "cloudflare-images"
    | "cloudflare-stream"
    | "insperia-privacy";
  primaryGuest?: string;
  type: string;
  sharedGuests?: string[];
  spaceCategory?: string;
  space?: string | null;
  /**
   *  reserved - confirmed by both parties, before check-in
   *  checkedIn - checked in
   *  checkedOut - checked out
   *  cancelled - Cancelled
   *  noShow - No show
   *  enquired - Confirmed neither by the customer nor enterprise
   *  requested - Confirmed by the customer but not the enterprise (waitlist)
   *  optional - Confirmed by the enterprise but not the customer (holding)
   */
  status: "reserved" | "checkedIn" | "checkedOut" | "cancelled" | "noShow" | "enquired" | "requested" | "optional";
  /**
   * spaceCategory has changed from original.
   */
  mobileCheckInSpaceCategoryChanged?: boolean;
  mobileCheckInSpaceChanged?: boolean;
  mobileCheckInStatus?:
    | "ready"
    | "blocked"
    | "preArrivalStepsRequired"
    | "spaceNotAssigned"
    | "spaceNotReady"
    | "checkInTimeNotStarted";
  mobileCheckInStatusMessage?: string;
  confirmationNumber?: string;
  /**
   * Expected arrival time of guest.
   */
  expectedCheckInDateTime?:
    | string
    | {
        [k: string]: unknown;
      };
  checkInDateTime:
    | string
    | {
        [k: string]: unknown;
      };
  checkOutDateTime:
    | string
    | {
        [k: string]: unknown;
      };
  adultCount?: number;
  childCount?: number;
  spaceCategoryAvailabilites?: {
    id?: string;
    price?: number;
    unit?: "night" | "stay" | "hour";
    isUpgrade?: boolean;
    [k: string]: unknown;
  }[];
  revenue?: Revenue;
  rateSuppressed?: boolean;
  payment?: string;
  company?: string;
  travelAgent?: string;
  systemId?: string;
  metadata?: {
    [k: string]: unknown;
  };
  updatedAt?: UpdatedAt;
  [k: string]: unknown;
}
