/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A room represents a physical space of controllable IoT devices
 */
export interface Scene {
  id?: string;
  name?: string;
  description?: string;
  devices?: {
    switches?: {
      id?: string;
      state?: "on" | "off";
      [k: string]: unknown;
    }[];
    dimmers?: {
      id?: string;
      level?: number | null;
      [k: string]: unknown;
    }[];
    windowCoverings?: {
      id?: string;
      position?: number | null;
      [k: string]: unknown;
    }[];
    thermostats?: {
      id?: string;
      hvacMode?: "cool" | "heat" | "auto" | "off";
      setpoints?: Setpoints;
      fanMode?: "auto" | "low" | "medium" | "high" | "off" | "on";
      setpointDelta?: number;
      [k: string]: unknown;
    }[];
    mediaSources?: {
      id?: string;
      volume?: number;
      commands?: string[];
      [k: string]: unknown;
    }[];
  };
  isDefault?: boolean;
  showOnUi?: boolean;
}
export interface Setpoints {
  cool?: Setpoint;
  heat?: Setpoint;
  auto?: Setpoint;
}
export interface Setpoint {
  value?: number;
  min?: number | null;
  max?: number | null;
}
