/* tslint:disable */
/* eslint-disable */
/**
 * This file is generated by core-types-ts on behalf of typeconv, DO NOT EDIT.
 * For more information, see:
 *  - {@link https://github.com/grantila/core-types-ts}
 *  - {@link https://github.com/grantila/typeconv}
 */

export interface ShortLinkSchema {
    id?: string;
    /**
     * @default
     *     shortLink
     */
    type?: string;
    title?: string;
    destination: any;
    url: any;
    systemId?: string;
    [key: string]: any;
}
