/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Date =
  | string
  | {
      [k: string]: unknown;
    };

export interface SMSMessage {
  id?: string;
  type?: string;
  to: string;
  from: string;
  media?: string;
  status:
    | "queued"
    | "accepted"
    | "sending"
    | "sent"
    | "failed"
    | "delivered"
    | "undelivered"
    | "receiving"
    | "received"
    | "read";
  body?: string;
  driver?: string;
  appData?: {
    [k: string]: unknown;
  };
  createdAt?: Date;
  updatedAt?: Date;
  systemId?: string;
  [k: string]: unknown;
}
