/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Space {
  id?: string;
  name?: string;
  type?: string;
  discriminator?:
    | "classRoom"
    | "hotelRoom"
    | "office"
    | "building"
    | "commonArea"
    | "conferenceRoom"
    | "lobby"
    | "gym"
    | "pool"
    | "restaurant";
  driver?:
    | "aws-kinesis"
    | "butler"
    | "crestron"
    | "dmp"
    | "dormakaba"
    | "dsc"
    | "ecobee"
    | "igor"
    | "inncom"
    | "kohost-k7"
    | "kohost-pms"
    | "lg"
    | "lirc"
    | "mews"
    | "mht"
    | "paxton"
    | "pelican-wireless"
    | "power-shades"
    | "rebrandly"
    | "salto"
    | "salto-irn"
    | "se"
    | "sendgrid"
    | "sonifi"
    | "stay-n-touch"
    | "twilio"
    | "cloudflare-images"
    | "cloudflare-stream"
    | "insperia-privacy";
  /**
   * This is the category id
   */
  category?: string;
  rooms?: string[];
  subGroups?: string[];
  occupied?: boolean;
  eco?: {
    active?: boolean;
    activatedAt?:
      | string
      | {
          [k: string]: unknown;
        };
    allowed?: boolean;
  };
  features?: string[];
  maximumOccupancy?: number;
  housekeepingStatus?: "clean" | "dirty" | "inspected" | "pickup";
  serviceStatus?: "inService" | "outOfOrder" | "outOfService";
  systemId?: string;
  [k: string]: unknown;
}
