/* tslint:disable */
/* eslint-disable */
/**
 * This file is generated by core-types-ts on behalf of typeconv, DO NOT EDIT.
 * For more information, see:
 *  - {@link https://github.com/grantila/core-types-ts}
 *  - {@link https://github.com/grantila/typeconv}
 */

/** A system user is a user that originated from an external 3rd party system. */
export interface SystemUserSchema {
    id?: string;
    /**
     * @default
     *     systemUser
     */
    type?: string;
    driver?: "aws-kinesis" | "butler" | "crestron" | "dmp" | "dormakaba" | "dsc" | "ecobee" | "igor" | "inncom" | "kohost-k7" | "kohost-pms" | "lg" | "lirc" | "mews" | "mht" | "paxton" | "pelican-wireless" | "power-shades" | "rebrandly" | "salto" | "salto-irn" | "se" | "sendgrid" | "sonifi" | "stay-n-touch" | "twilio" | "cloudflare-images" | "cloudflare-stream" | "insperia-privacy";
    firstName: string;
    lastName: string;
    phone?: string | null;
    email?: string | null;
    address?: {
        id?: string;
        line1?: string;
        line2?: string;
        line3?: string;
        city?: string;
        state?: string;
        postalCode?: string;
        countryCode?: string;
        [key: string]: any;
    };
    photo?: string;
    jobTitle?: string;
    dob?: string;
    gender?: "male" | "female";
    roles?: ("Guest" | "User" | "Manager" | "Administrator" | "SuperAdmin")[];
    nationality?: string;
    notes?: string[];
    files?: {
        id?: string;
        /**
         * @default
         *     mediaFile
         */
        type: string;
        name?: string;
        fileHash?: string;
        mimeType?: "image/*" | "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/avif" | "image/svg+xml" | "application/pdf";
        data?: string;
        url?: string;
        width?: number;
        height?: number;
        /** Size in bytes */
        size?: number;
        uploadUrl?: string;
        uploadUrlExpires?: string | {
            [key: string]: any;
        };
        createdBy?: string;
        systemId?: string;
    }[];
    identifications?: {
        id?: string;
        type: "driversLicense" | "passport" | "identityCard" | "visa";
        number?: any;
        maskedNumber?: any;
        encryptedNumber?: any;
        issued?: string | {
            [key: string]: any;
        };
        expires?: string | {
            [key: string]: any;
        } | null;
        verified?: boolean;
        matched?: boolean;
        firstName?: string;
        lastName?: string;
        issuingCountry?: any;
        systemId?: string;
        [key: string]: any;
    }[];
    payments?: {
        id?: string;
        type: "amex" | "visa" | "masterCard" | "maestro" | "discover" | "diners" | "jcb" | "applePay" | "alipay" | "chinaUnionPay" | "vpay";
        /**
         * @default
         *     true
         */
        enabled?: boolean;
        storageData?: string | null;
        maskedNumber: any;
        issued?: string | null;
        expires: any;
        systemId?: string;
        [key: string]: any;
    }[];
    revenue?: {
        id?: string;
        name?: string;
        date?: string;
        price?: number;
        tax?: number | null;
        [key: string]: any;
    }[];
    createdAt?: string | {
        [key: string]: any;
    };
    updatedAt?: string | {
        [key: string]: any;
    };
    systemId?: string;
    [key: string]: any;
}
