/* tslint:disable */
/* eslint-disable */
/**
 * This file is generated by core-types-ts on behalf of typeconv, DO NOT EDIT.
 * For more information, see:
 *  - {@link https://github.com/grantila/core-types-ts}
 *  - {@link https://github.com/grantila/typeconv}
 */

/** A ticket is a request from a user. */
export interface TicketSchema {
    id: string;
    /**
     * @default
     *     ticket
     */
    type?: "ticket";
    /**
     * @default
     *     []
     */
    conversation: {
        id?: string;
        userId?: string;
        userName?: string;
        systemId?: string;
        systemName?: string;
        timestamp?: string | {
            [key: string]: any;
        };
        body?: string;
        /**
         * @default
         *     []
         */
        readBy?: string[];
        media?: /** Any media file */
        {
            id?: string;
            /**
             * @default
             *     mediaFile
             */
            type: string;
            name?: string;
            fileHash?: string;
            mimeType?: "image/*" | "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/avif" | "image/svg+xml" | "application/pdf";
            data?: string;
            url?: string;
            width?: number;
            height?: number;
            /** Size in bytes */
            size?: number;
            uploadUrl?: string;
            uploadUrlExpires?: string | {
                [key: string]: any;
            };
            createdBy?: string;
            systemId?: string;
        } | null;
    }[];
    openedBy?: {
        userId?: string;
        [key: string]: any;
    };
    requester: {
        systemId?: string;
        systemName?: string;
        systemPhoto?: /** Any media file */
        {
            id?: string;
            /**
             * @default
             *     mediaFile
             */
            type: string;
            name?: string;
            fileHash?: string;
            mimeType?: "image/*" | "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/avif" | "image/svg+xml" | "application/pdf";
            data?: string;
            url?: string;
            width?: number;
            height?: number;
            /** Size in bytes */
            size?: number;
            uploadUrl?: string;
            uploadUrlExpires?: string | {
                [key: string]: any;
            };
            createdBy?: string;
            systemId?: string;
        } | null | string;
        userId?: string;
        userName?: string;
        userPhoto?: /** Any media file */
        {
            id?: string;
            /**
             * @default
             *     mediaFile
             */
            type: string;
            name?: string;
            fileHash?: string;
            mimeType?: "image/*" | "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/avif" | "image/svg+xml" | "application/pdf";
            data?: string;
            url?: string;
            width?: number;
            height?: number;
            /** Size in bytes */
            size?: number;
            uploadUrl?: string;
            uploadUrlExpires?: string | {
                [key: string]: any;
            };
            createdBy?: string;
            systemId?: string;
        } | null | string;
        deviceId?: string;
        roomId?: string;
        spaceId?: string;
        spaceName?: string;
        [key: string]: any;
    };
    assignedTo?: {
        userId?: string;
        userName?: string;
        userPhoto?: /** Any media file */
        {
            id?: string;
            /**
             * @default
             *     mediaFile
             */
            type: string;
            name?: string;
            fileHash?: string;
            mimeType?: "image/*" | "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/avif" | "image/svg+xml" | "application/pdf";
            data?: string;
            url?: string;
            width?: number;
            height?: number;
            /** Size in bytes */
            size?: number;
            uploadUrl?: string;
            uploadUrlExpires?: string | {
                [key: string]: any;
            };
            createdBy?: string;
            systemId?: string;
        } | null | string;
        [key: string]: any;
    };
    /**
     * @default
     *     open
     */
    status: "open" | "pending" | "solved" | "closed";
    /**
     * @default
     *     []
     */
    tags: string[];
    rating?: number;
    ratingComment?: string;
    tipAmount?: string;
    createdAt: string | {
        [key: string]: any;
    };
    updatedAt: string | {
        [key: string]: any;
    };
    solvedAt?: string | {
        [key: string]: any;
    };
    closedAt?: string | {
        [key: string]: any;
    };
}
