/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Date =
  | string
  | {
      [k: string]: unknown;
    };

/**
 * A ticket is a request from a user.
 */
export interface Ticket {
  id: string;
  type?: "ticket";
  conversation: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  )[];
  openedBy?: {
    userId?: string;
    [k: string]: unknown;
  };
  requester: {
    systemId?: string;
    systemName?: string;
    systemPhoto?: MediaFile | null | string;
    userId?: string;
    userName?: string;
    userPhoto?: MediaFile | null | string;
    deviceId?: string;
    roomId?: string;
    spaceId?: string;
    spaceName?: string;
    [k: string]: unknown;
  };
  assignedTo?: {
    userId?: string;
    userName?: string;
    userPhoto?: MediaFile | null | string;
    [k: string]: unknown;
  };
  status: "open" | "pending" | "solved" | "closed";
  tags: string[];
  rating?: number;
  ratingComment?: string;
  tipAmount?: string;
  createdAt: Date;
  updatedAt: Date;
  solvedAt?: Date;
  closedAt?: Date;
}
/**
 * Any media file
 */
export interface MediaFile {
  id?: string;
  type: string;
  name?: string;
  fileHash?: string;
  mimeType?:
    | "image/*"
    | "image/jpeg"
    | "image/png"
    | "image/gif"
    | "image/webp"
    | "image/avif"
    | "image/svg+xml"
    | "application/pdf";
  data?: string;
  url?: string;
  width?: number;
  height?: number;
  /**
   * Size in bytes
   */
  size?: number;
  uploadUrl?: string;
  uploadUrlExpires?: Date;
  createdBy?: string;
  systemId?: string;
}
