/* tslint:disable */
/* eslint-disable */
/**
 * This file is generated by core-types-ts on behalf of typeconv, DO NOT EDIT.
 * For more information, see:
 *  - {@link https://github.com/grantila/core-types-ts}
 *  - {@link https://github.com/grantila/typeconv}
 */

export interface UserSchema {
    id?: string;
    /**
     * @default
     *     user
     */
    type?: string;
    firstName: string;
    lastName: string;
    phone?: string | null;
    phoneVerified?: boolean;
    email?: string | null;
    emailVerified?: boolean;
    address?: {
        id?: string;
        line1?: string;
        line2?: string;
        line3?: string;
        city?: string;
        state?: string;
        postalCode?: string;
        countryCode?: string;
        [key: string]: any;
    };
    secretKey?: string;
    /** Any media file */
    photo?: {
        id?: string;
        /**
         * @default
         *     mediaFile
         */
        type: string;
        name?: string;
        fileHash?: string;
        mimeType?: "image/*" | "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/avif" | "image/svg+xml" | "application/pdf";
        data?: string;
        url?: string;
        width?: number;
        height?: number;
        /** Size in bytes */
        size?: number;
        uploadUrl?: string;
        uploadUrlExpires?: string | {
            [key: string]: any;
        };
        createdBy?: string;
        systemId?: string;
    };
    jobTitle?: string;
    dob?: string;
    gender?: "male" | "female";
    nationality?: string;
    /**
     * @default
     *     []
     */
    permissions?: {
        /** The ID of the organization the permission is applies to. */
        organization: string;
        /** The ID of the property the permission is applies to. */
        property: string;
        role: "Guest" | "User" | "Manager" | "Administrator" | "SuperAdmin";
        customPermissions?: {
            discriminator?: "RoomControl.spaces" | "Concierge.timeTracking";
            onlyIncludeIds?: string[];
            [key: string]: any;
        }[];
    }[];
    notes?: string[];
    files?: {
        id?: string;
        /**
         * @default
         *     mediaFile
         */
        type: string;
        name?: string;
        fileHash?: string;
        mimeType?: "image/*" | "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/avif" | "image/svg+xml" | "application/pdf";
        data?: string;
        url?: string;
        width?: number;
        height?: number;
        /** Size in bytes */
        size?: number;
        uploadUrl?: string;
        uploadUrlExpires?: string | {
            [key: string]: any;
        };
        createdBy?: string;
        systemId?: string;
    }[];
    identifications?: {
        id?: string;
        type: "driversLicense" | "passport" | "identityCard" | "visa";
        number?: any;
        maskedNumber?: any;
        encryptedNumber?: any;
        issued?: string | {
            [key: string]: any;
        };
        expires?: string | {
            [key: string]: any;
        } | null;
        verified?: boolean;
        matched?: boolean;
        firstName?: string;
        lastName?: string;
        issuingCountry?: any;
        systemId?: string;
        [key: string]: any;
    }[];
    payments?: {
        id?: string;
        type: "amex" | "visa" | "masterCard" | "maestro" | "discover" | "diners" | "jcb" | "applePay" | "alipay" | "chinaUnionPay" | "vpay";
        /**
         * @default
         *     true
         */
        enabled?: boolean;
        storageData?: string | null;
        maskedNumber: any;
        issued?: string | null;
        expires: any;
        systemId?: string;
        [key: string]: any;
    }[];
    location?: {
        accuracy: number | null;
        latitude: number | null;
        longitude: number | null;
        timestamp: number | null;
    };
    reservations?: {
        id?: string;
        driver?: "aws-kinesis" | "butler" | "crestron" | "dmp" | "dormakaba" | "dsc" | "ecobee" | "igor" | "inncom" | "kohost-k7" | "kohost-pms" | "lg" | "lirc" | "mews" | "mht" | "paxton" | "pelican-wireless" | "power-shades" | "rebrandly" | "salto" | "salto-irn" | "se" | "sendgrid" | "sonifi" | "stay-n-touch" | "twilio" | "cloudflare-images" | "cloudflare-stream" | "insperia-privacy";
        primaryGuest?: string;
        /**
         * @default
         *     reservation
         */
        type: string;
        sharedGuests?: string[];
        spaceCategory?: string;
        space?: string | null;
        /**
         * reserved - confirmed by both parties, before check-in
         *  checkedIn - checked in
         *  checkedOut - checked out
         *  cancelled - Cancelled
         *  noShow - No show
         *  enquired - Confirmed neither by the customer nor enterprise
         *  requested - Confirmed by the customer but not the enterprise (waitlist)
         *  optional - Confirmed by the enterprise but not the customer (holding)
         */
        status: "reserved" | "checkedIn" | "checkedOut" | "cancelled" | "noShow" | "enquired" | "requested" | "optional";
        /** spaceCategory has changed from original. */
        mobileCheckInSpaceCategoryChanged?: boolean;
        mobileCheckInSpaceChanged?: boolean;
        mobileCheckInStatus?: "ready" | "blocked" | "preArrivalStepsRequired" | "spaceNotAssigned" | "spaceNotReady" | "checkInTimeNotStarted";
        mobileCheckInStatusMessage?: string;
        confirmationNumber?: string;
        expectedCheckInDateTime?: /** Expected arrival time of guest. */
        string | /** Expected arrival time of guest. */
        {
            [key: string]: any;
        };
        checkInDateTime: string | {
            [key: string]: any;
        };
        checkOutDateTime: string | {
            [key: string]: any;
        };
        /**
         * @default
         *     1
         */
        adultCount?: number;
        childCount?: number;
        spaceCategoryAvailabilites?: {
            id?: string;
            price?: number;
            unit?: "night" | "stay" | "hour";
            isUpgrade?: boolean;
            [key: string]: any;
        }[];
        revenue?: {
            id?: string;
            name?: string;
            date?: string;
            price?: number;
            tax?: number | null;
            [key: string]: any;
        }[];
        rateSuppressed?: boolean;
        payment?: string;
        company?: string;
        travelAgent?: string;
        systemId?: string;
        metadata?: any;
        updatedAt?: string | {
            [key: string]: any;
        };
        [key: string]: any;
    }[];
    spaceName?: string;
    revenue?: {
        id?: string;
        name?: string;
        date?: string;
        price?: number;
        tax?: number | null;
        [key: string]: any;
    }[];
    createdAt?: string | {
        [key: string]: any;
    };
    updatedAt?: string | {
        [key: string]: any;
    };
    /**
     * @default
     *     []
     */
    systems?: {
        systemId: string;
        property: string;
        driver: string;
    }[];
    [key: string]: any;
}
