export { alarmSchema, type AlarmSchema } from "./alarm.js";
export { announcementSchema, type AnnouncementSchema } from "./announcement.js";
export { automationSchema, type AutomationSchema } from "./automation.js";
export { cameraSchema, type CameraSchema } from "./camera.js";
export { categorySchema, type CategorySchema } from "./category.js";
export { courtesySchema, type CourtesySchema } from "./courtesy.js";
export { credentialSchema, type CredentialSchema } from "./credential.js";
export { departmentSchema, type DepartmentSchema } from "./department.js";
export { deviceRouterSchema, type DeviceRouterSchema } from "./deviceRouter.js";
export { dimmerSchema, type DimmerSchema } from "./dimmer.js";
export { discoveredDeviceSchema, type DiscoveredDeviceSchema } from "./discoveredDevice.js";
export { emailMessageSchema, type EmailMessageSchema } from "./emailMessage.js";
export { energyReportSchema, type EnergyReportSchema } from "./energyReport.js";
export { energyReportShardSchema, type EnergyReportShardSchema } from "./energyReportShard.js";
export { gatewaySchema, type GatewaySchema } from "./gateway.js";
export { identificationSchema, type IdentificationSchema } from "./identification.js";
export { issueSchema, type IssueSchema } from "./issue.js";
export { lockSchema, type LockSchema } from "./lock.js";
export { logSchema, type LogSchema } from "./log.js";
export { mediaFileSchema, type MediaFileSchema, methods as mediaFileMethods } from "./mediaFile.js";
export { mediaSourceSchema, type MediaSourceSchema } from "./mediaSource.js";
export { motionSensorSchema, type MotionSensorSchema } from "./motionSensor.js";
export { notificationSchema, type NotificationSchema } from "./notification.js";
export { orderSchema, type OrderSchema, methods as orderMethods } from "./order.js";
export { organizationSchema, type OrganizationSchema } from "./organization.js";
export { paymentSchema, type PaymentSchema } from "./payment.js";
export { policySchema, type PolicySchema } from "./policy.js";
export { productSchema, type ProductSchema } from "./product.js";
export { propertySchema, type PropertySchema } from "./property.js";
export { reservationSchema, type ReservationSchema, methods as reservationMethods } from "./reservation.js";
export { roomSchema, type RoomSchema, getters as roomGetters, statics as roomStatics } from "./room.js";
export { sceneSchema, type SceneSchema } from "./scene.js";
export { serverSchema, type ServerSchema } from "./server.js";
export { sessionSchema, type SessionSchema } from "./session.js";
export { shortLinkSchema, type ShortLinkSchema } from "./shortLink.js";
export { smsMessageSchema, type SmsMessageSchema } from "./smsMessage.js";
export { spaceSchema, type SpaceSchema, getters as spaceGetters } from "./space.js";
export { switchSchema, type SwitchSchema } from "./switch.js";
export { systemSchema, type SystemSchema } from "./system.js";
export { systemUserSchema, type SystemUserSchema } from "./systemUser.js";
export { thermostatSchema, type ThermostatSchema } from "./thermostat.js";
export { ticketSchema, type TicketSchema } from "./ticket.js";
export { timeSheetSchema, type TimeSheetSchema } from "./timeSheet.js";
export { userSchema, type UserSchema, getters as userGetters } from "./user.js";
export { vendorSchema, type VendorSchema } from "./vendor.js";
export { windowCoveringSchema, type WindowCoveringSchema } from "./windowCovering.js";
