/* @ts-nocheck */
/* This file is automatically generated. Do not modify it manually. */

import { Entity } from "./entity";
import { validateAlarm as validate } from "../validate";

/**
 * @typedef {Object} AlarmData Any smart alarm system
 * @property {string} id - Identifier of the object.
 * @property {string} [name] - Name of the alarm
 * @property {boolean} [offline]
 * @property {"alarm"} type - Default: "alarm"
 * @property {string} [systemId] - Identifier of the object, directly related to the system.
 * @property {("adlink"|"aws-kinesis"|"bacnet"|"benq"|"butler"|"comelit"|"crestron"|"dell"|"digital-watchdog"|"distech"|"dmp"|"doorbird"|"dormakaba"|"dsc"|"dsc-itv2"|"ecobee"|"epson"|"geovision-rs"|"geovision-as-manager"|"honeywell-vista"|"igor"|"inncom"|"isapi"|"kohost-k7"|"kohost"|"lg"|"lg-webos"|"lapi"|"lirc"|"mews"|"mht"|"newline"|"paxton"|"pelican-wireless"|"power-shades"|"rachio"|"rebrandly"|"relay"|"rtsp"|"salto"|"salto-irn"|"samsung"|"se"|"sendgrid"|"smartboard"|"sonifi"|"stay-n-touch"|"storable"|"twilio"|"unifi"|"valcom"|"veracross"|"vivotek"|"vizio"|"wisenet"|"cloudflare-images"|"cloudflare-stream"|"insperia-privacy")} driver - Driver used to communicate with the object.
 * @property {{id?: string, name?: string, supportedSecurityModes?: ("arming"|"disarming"|"armed"|"disarmed"|"intrusion"|"fire"|"medical")[], securityMode?: ("arming"|"disarming"|"armed"|"disarmed"|"intrusion"|"fire"|"medical")}[]} areas
 * @property {{id?: string, name?: string, secure?: (boolean|null), bypassed?: (boolean|null), offline?: boolean, batteryLevel?: number}[]} zones
 * @property {string} [code]
 * @property {boolean} [chime] - Chime enabled
 * @property {number} [watts]
 * @property {string} [icon]
 * @property {string} [manufacturer]
 * @property {string} [modelNumber]
 * @property {string} [serialNumber]
 * @property {string} [firmwareVersion]
 * @property {{id?: string, line1?: string, line2?: string, line3?: string, city?: string, state?: string, postalCode?: string, countryCode?: string}} [address]
 * @property {number} [batteryLevel]
 * @property {number} [powerLevel]
 * @property {boolean} [monitoringTrouble]
 * @property {boolean} [bellTrouble]
 */

/**
 * Any smart alarm system
 * @class Alarm
 * @extends {Entity}
 */
export class Alarm extends Entity {
  /**
   * @constructor
   * @param {AlarmData} data - The data to initialize the Alarm with
   */
  constructor(data) {
    super(data);
    this.id = data.id;
    if (data.name !== undefined) this.name = data.name;
    if (data.offline !== undefined) this.offline = data.offline;
    this.type = data.type;
    if (data.systemId !== undefined) this.systemId = data.systemId;
    this.driver = data.driver;
    this.areas = data.areas;
    this.zones = data.zones;
    if (data.code !== undefined) this.code = data.code;
    if (data.chime !== undefined) this.chime = data.chime;
    if (data.watts !== undefined) this.watts = data.watts;
    if (data.icon !== undefined) this.icon = data.icon;
    if (data.manufacturer !== undefined) this.manufacturer = data.manufacturer;
    if (data.modelNumber !== undefined) this.modelNumber = data.modelNumber;
    if (data.serialNumber !== undefined) this.serialNumber = data.serialNumber;
    if (data.firmwareVersion !== undefined)
      this.firmwareVersion = data.firmwareVersion;
    if (data.address !== undefined) this.address = data.address;
    if (data.batteryLevel !== undefined) this.batteryLevel = data.batteryLevel;
    if (data.powerLevel !== undefined) this.powerLevel = data.powerLevel;
    if (data.monitoringTrouble !== undefined)
      this.monitoringTrouble = data.monitoringTrouble;
    if (data.bellTrouble !== undefined) this.bellTrouble = data.bellTrouble;
  }
}

Object.defineProperty(Alarm.prototype, "schema", {
  value: {
    $schema: "http://json-schema.org/draft-07/schema",
    $id: "alarm.json",
    title: "Alarm",
    description: "Any smart alarm system",
    type: "object",
    $defs: {
      securityMode: {
        type: ["string", "null"],
        enum: [
          "arming",
          "disarming",
          "armed",
          "disarmed",
          "intrusion",
          "fire",
          "medical",
          null,
        ],
      },
    },
    required: ["id", "type", "areas", "zones", "driver"],
    additionalProperties: false,
    properties: {
      id: { $ref: "definitions.json#/definitions/id" },
      name: { type: "string", description: "Name of the alarm" },
      offline: { type: "boolean" },
      type: { type: "string", enum: ["alarm"], default: "alarm" },
      systemId: { $ref: "definitions.json#/definitions/systemId" },
      driver: { $ref: "definitions.json#/definitions/driver" },
      areas: {
        type: "array",
        items: {
          type: "object",
          properties: {
            id: { $ref: "definitions.json#/definitions/id" },
            name: { type: "string" },
            supportedSecurityModes: {
              type: "array",
              items: { $ref: "#/$defs/securityMode" },
            },
            securityMode: { $ref: "#/$defs/securityMode" },
          },
          additionalProperties: false,
        },
      },
      zones: {
        type: "array",
        items: {
          type: "object",
          properties: {
            id: { $ref: "definitions.json#/definitions/id" },
            name: { type: "string" },
            secure: { type: ["boolean", "null"] },
            bypassed: { type: ["boolean", "null"] },
            offline: { type: "boolean" },
            batteryLevel: {
              $ref: "definitions.json#/definitions/batteryLevel",
            },
          },
          additionalProperties: false,
        },
      },
      code: { type: "string" },
      chime: { type: "boolean", description: "Chime enabled" },
      watts: { $ref: "definitions.json#/definitions/watts" },
      icon: { type: "string" },
      manufacturer: { type: "string" },
      modelNumber: { type: "string" },
      serialNumber: { type: "string" },
      firmwareVersion: { type: "string" },
      address: { $ref: "definitions.json#/definitions/address" },
      batteryLevel: { $ref: "definitions.json#/definitions/batteryLevel" },
      powerLevel: { $ref: "definitions.json#/definitions/batteryLevel" },
      monitoringTrouble: { type: "boolean" },
      bellTrouble: { type: "boolean" },
    },
  },
});

Object.defineProperty(Alarm.prototype, "validator", {
  get: function () {
    return validate;
  },
});
