// This file is automatically generated. Do not modify it manually.

  import { Entity } from './entity';
  import { validateAnnouncement as validate } from '../validators/announcement';

  export class Announcement extends Entity {
	constructor(data) {
	  super(data);
	  this.id = data.id;
            this.type = data.type;
            this.users = data.users;
            this.group = data.group;
            this.body = data.body;
            this.media = data.media;
            this.sentBy = data.sentBy;
            this.tags = data.tags;
            this.createdAt = data.createdAt;
            this.updatedAt = data.updatedAt;
	}
	  

	
	  
	  

	  

	  
  }

  Object.defineProperty(Announcement.prototype, "schema", {
	value: {"$schema":"http://json-schema.org/draft-07/schema","$id":"announcement.json","title":"Announcement","description":"Announcement message sent to users","type":"object","properties":{"id":{"$ref":"definitions.json#/definitions/id"},"type":{"type":"string","enum":["announcement"],"default":"announcement"},"users":{"type":"array","items":{"type":"string"},"minItems":1},"group":{"type":"string"},"body":{"type":"string"},"media":{"$ref":"mediaFile.json"},"sentBy":{"type":"string"},"tags":{"type":"array","items":{"type":"string"}},"createdAt":{"$ref":"definitions.json#/definitions/date"},"updatedAt":{"$ref":"definitions.json#/definitions/date"}},"additionalProperties":false}
  });

  Object.defineProperty(Announcement.prototype, "validator", {
	get: function() { return validate; }
  });
