// This file is automatically generated. Do not modify it manually.

  import { Entity } from './entity';
  import { validateCredential as validate } from '../validators/credential';

  export class Credential extends Entity {
	constructor(data) {
	  super(data);
	  this.id = data.id;
            this.type = data.type;
            this.driver = data.driver;
            this.discriminator = data.discriminator;
            this.credential = data.credential;
            this.userId = data.userId;
            this.organizationId = data.organizationId;
            this.propertyId = data.propertyId;
            this.deviceId = data.deviceId;
            this.userAgent = data.userAgent;
            this.expires = data.expires;
            this.systemId = data.systemId;
	}
	  

	
	  
	  

	  

	  
  }

  Object.defineProperty(Credential.prototype, "schema", {
	value: {"$schema":"http://json-schema.org/draft-07/schema","$id":"credential.json","title":"Credential","type":"object","required":["type","credential","expires"],"properties":{"id":{"$ref":"definitions.json#/definitions/id"},"type":{"type":"string","default":"credential"},"driver":{"$ref":"definitions.json#/definitions/driver"},"discriminator":{"type":"string","enum":["verificationCode","token","mobileKey","pin","publicKey","passkeyChallenge"]},"credential":{"type":"string"},"userId":{"type":"string"},"organizationId":{"type":"string"},"propertyId":{"type":"string"},"deviceId":{"type":"string"},"userAgent":{"type":"string"},"expires":{"type":["string","object","null"]},"systemId":{"$ref":"definitions.json#/definitions/systemId"}}}
  });

  Object.defineProperty(Credential.prototype, "validator", {
	get: function() { return validate; }
  });
