// This file is automatically generated. Do not modify it manually.

  import { Entity } from './entity';
  import { validateLock as validate } from '../validators/lock';

  export class Lock extends Entity {
	constructor(data) {
	  super(data);
	  this.id = data.id;
            this.name = data.name;
            this.type = data.type;
            this.offline = data.offline;
            this.supportedNotifications = data.supportedNotifications;
            this.notification = data.notification;
            this.driver = data.driver;
            this.state = data.state;
            this.mode = data.mode;
            this.supportedModes = data.supportedModes;
            this.batteryLevel = data.batteryLevel;
            this.systemId = data.systemId;
            this.watts = data.watts;
	}
	  

	
	  
	  

	  

	  
  }

  Object.defineProperty(Lock.prototype, "schema", {
	value: {"$schema":"http://json-schema.org/draft-07/schema","$id":"lock.json","title":"Lock","description":"Any smart lock","type":"object","properties":{"id":{"$ref":"definitions.json#/definitions/id"},"name":{"type":"string"},"type":{"$ref":"definitions.json#/definitions/type"},"offline":{"type":"boolean"},"supportedNotifications":{"$ref":"definitions.json#/definitions/supportedNotifications"},"notification":{"$ref":"definitions.json#/definitions/notification"},"driver":{"$ref":"definitions.json#/definitions/driver"},"state":{"type":["string","null"],"enum":["locked","unlocked",null]},"mode":{"type":["string","null"],"enum":["normal","autoLock","emergencyOpen","emergencyClose","holdOpen","lockdown",null],"description":"emergencyOpen and emergencyClose are deprecated and can be removed once Salto, Paxton and Geovision drivers are updated","default":null},"supportedModes":{"type":"array","uniqueItems":true,"items":{"enum":["normal","autoLock","emergencyOpen","emergencyClose","holdOpen","lockdown",null]}},"batteryLevel":{"$ref":"definitions.json#/definitions/batteryLevel"},"systemId":{"$ref":"definitions.json#/definitions/systemId"},"watts":{"$ref":"definitions.json#/definitions/watts"}},"required":["id","type","state","driver"]}
  });

  Object.defineProperty(Lock.prototype, "validator", {
	get: function() { return validate; }
  });
