/* @ts-nocheck */
/* This file is automatically generated. Do not modify it manually. */

import { Entity } from "./entity";
import { validatePolicy as validate } from "../validators";

export class Policy extends Entity {
  /**
   * @typedef {Object} PolicyData A policy is a set of permissions that can be applied to a user to limit their access to resources.
   * @property {string} [id] - Identifier of the object.
   * @property {"policy"} type - Default: "policy"
   * @property {"user"} discriminator
   * @property {string} name
   * @property {string} [description]
   * @property {string} organizationId
   * @property {string} propertyId
   * @property {{entities: string[], effect: ("Allow"|"Deny")}[]} permissions
   */

  /**
   * @param {PolicyData} data - The data to initialize the Policy with
   * @constructor
   */
  constructor(data) {
    super(data);
    if (data.id !== undefined) this.id = data.id;
    if (data.type !== undefined) this.type = data.type;
    if (data.discriminator !== undefined)
      this.discriminator = data.discriminator;
    if (data.name !== undefined) this.name = data.name;
    if (data.description !== undefined) this.description = data.description;
    if (data.organizationId !== undefined)
      this.organizationId = data.organizationId;
    if (data.propertyId !== undefined) this.propertyId = data.propertyId;
    if (data.permissions !== undefined) this.permissions = data.permissions;
  }
}

Object.defineProperty(Policy.prototype, "schema", {
  value: {
    $schema: "http://json-schema.org/draft-07/schema",
    $id: "policy.json",
    title: "Policy",
    description:
      "A policy is a set of permissions that can be applied to a user to limit their access to resources.",
    type: "object",
    required: [
      "name",
      "type",
      "organizationId",
      "propertyId",
      "permissions",
      "discriminator",
    ],
    properties: {
      id: { $ref: "definitions.json#/definitions/id" },
      type: { type: "string", default: "policy", enum: ["policy"] },
      discriminator: { type: "string", enum: ["user"] },
      name: { type: "string", minLength: 1 },
      description: { type: "string" },
      organizationId: { type: "string" },
      propertyId: { type: "string" },
      permissions: {
        type: "array",
        items: {
          type: "object",
          required: ["entities", "effect"],
          properties: {
            entities: {
              type: "array",
              items: { type: "string", pattern: "^[^:]+(:.+)+$" },
            },
            effect: { type: "string", enum: ["Allow", "Deny"] },
          },
        },
      },
    },
  },
});

Object.defineProperty(Policy.prototype, "validator", {
  get: function () {
    return validate;
  },
});
