/* @ts-nocheck */
/* This file is automatically generated. Do not modify it manually. */

import { Entity } from "./entity";
import { validateServer as validate } from "../validate";

/**
 * @typedef {Object} ServerData A server is a physical or virtual machine that runs the Kohost software
 * @property {string} id - Identifier of the object.
 * @property {string} [name]
 * @property {"server"} type - Default: "server"
 * @property {{name?: string, mac?: string, ipv4?: string[], ipv6?: string[], state?: string}[]} [networkInterfaces]
 * @property {{id?: string, name?: string, image?: string, status?: string, state?: string, restartCount?: number, startedAt?: string}[]} [containers]
 * @property {{dockerVersion?: string, kernelVersion?: string}} [software]
 * @property {string} [hostname]
 * @property {string} [organizationId]
 * @property {string} [propertyId]
 * @property {string} [manufacturer]
 * @property {string} [modelNumber]
 * @property {string} [serialNumber]
 * @property {string} [operatingSystem]
 * @property {{offline?: boolean, cpuUsage?: number, memoryUsage?: number, diskUsage?: number, lastHeartbeatAt?: string}} [health]
 * @property {number} [watts]
 * @property {string} [virtualization]
 * @property {string} [bootedAt]
 * @property {string} [createdAt]
 * @property {string} [updatedAt]
 * @property {string} [deletedAt]
 * @property {string} [architecture]
 * @property {{cpuCores?: number, memoryTotal?: number, diskTotal?: number}} [resources]
 * @property {string} [timezone]
 */

/**
 * A server is a physical or virtual machine that runs the Kohost software
 * @class Server
 * @extends {Entity}
 */
export class Server extends Entity {
  /**
   * @constructor
   * @param {ServerData} data - The data to initialize the Server with
   */
  constructor(data) {
    super(data);
    this.id = data.id;
    if (data.name !== undefined) this.name = data.name;
    this.type = data.type;
    if (data.networkInterfaces !== undefined)
      this.networkInterfaces = data.networkInterfaces;
    if (data.containers !== undefined) this.containers = data.containers;
    if (data.software !== undefined) this.software = data.software;
    if (data.hostname !== undefined) this.hostname = data.hostname;
    if (data.organizationId !== undefined)
      this.organizationId = data.organizationId;
    if (data.propertyId !== undefined) this.propertyId = data.propertyId;
    if (data.manufacturer !== undefined) this.manufacturer = data.manufacturer;
    if (data.modelNumber !== undefined) this.modelNumber = data.modelNumber;
    if (data.serialNumber !== undefined) this.serialNumber = data.serialNumber;
    if (data.operatingSystem !== undefined)
      this.operatingSystem = data.operatingSystem;
    if (data.health !== undefined) this.health = data.health;
    if (data.watts !== undefined) this.watts = data.watts;
    if (data.virtualization !== undefined)
      this.virtualization = data.virtualization;
    if (data.bootedAt !== undefined) this.bootedAt = data.bootedAt;
    if (data.createdAt !== undefined) this.createdAt = data.createdAt;
    if (data.updatedAt !== undefined) this.updatedAt = data.updatedAt;
    if (data.deletedAt !== undefined) this.deletedAt = data.deletedAt;
    if (data.architecture !== undefined) this.architecture = data.architecture;
    if (data.resources !== undefined) this.resources = data.resources;
    if (data.timezone !== undefined) this.timezone = data.timezone;
  }
}

Object.defineProperty(Server.prototype, "schema", {
  value: {
    $schema: "http://json-schema.org/draft-07/schema",
    $id: "server.json",
    title: "Server",
    description:
      "A server is a physical or virtual machine that runs the Kohost software",
    type: "object",
    properties: {
      id: { $ref: "definitions.json#/definitions/id" },
      name: { type: "string" },
      type: { type: "string", enum: ["server"], default: "server" },
      networkInterfaces: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            mac: { type: "string" },
            ipv4: { type: "array", items: { type: "string" } },
            ipv6: { type: "array", items: { type: "string" } },
            state: { type: "string" },
          },
        },
      },
      containers: {
        type: "array",
        items: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            image: { type: "string" },
            status: { type: "string" },
            state: { type: "string" },
            restartCount: { type: "integer" },
            startedAt: { type: "string", format: "date-time" },
          },
        },
      },
      software: {
        type: "object",
        properties: {
          dockerVersion: { type: "string" },
          kernelVersion: { type: "string" },
        },
      },
      hostname: { type: "string" },
      organizationId: { type: "string" },
      propertyId: { type: "string" },
      manufacturer: { type: "string" },
      modelNumber: { type: "string" },
      serialNumber: { type: "string" },
      operatingSystem: { type: "string" },
      health: {
        type: "object",
        properties: {
          offline: { type: "boolean" },
          cpuUsage: { type: "number" },
          memoryUsage: { type: "number" },
          diskUsage: { type: "number" },
          lastHeartbeatAt: { type: "string", format: "date-time" },
        },
      },
      watts: { $ref: "definitions.json#/definitions/watts" },
      virtualization: { type: "string" },
      bootedAt: { type: "string", format: "date-time" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
      deletedAt: { type: "string", format: "date-time" },
      architecture: { type: "string" },
      resources: {
        type: "object",
        properties: {
          cpuCores: { type: "integer" },
          memoryTotal: { type: "integer" },
          diskTotal: { type: "integer" },
        },
      },
      timezone: { type: "string" },
    },
    required: ["id", "type"],
  },
});

Object.defineProperty(Server.prototype, "validator", {
  get: function () {
    return validate;
  },
});
