/* @ts-nocheck */
/* This file is automatically generated. Do not modify it manually. */

import { Entity } from "./entity";
import { validateShortLink as validate } from "../validate";

/**
 * @typedef {Object} ShortLinkData
 * @property {string} [id] - Identifier of the object.
 * @property {"shortLink"} [type] - Default: "shortLink"
 * @property {string} [title]
 * @property {string} destination
 * @property {string} url
 * @property {string} [systemId] - Identifier of the object, directly related to the system.
 * @property {(string|object)} [createdAt]
 * @property {(string|object)} [updatedAt]
 * @property {(string|object)} [deletedAt]
 */

/**
 *
 * @class ShortLink
 * @extends {Entity}
 */
export class ShortLink extends Entity {
  /**
   * @constructor
   * @param {ShortLinkData} data - The data to initialize the ShortLink with
   */
  constructor(data) {
    super(data);
    if (data.id !== undefined) this.id = data.id;
    if (data.type !== undefined) this.type = data.type;
    if (data.title !== undefined) this.title = data.title;
    this.destination = data.destination;
    this.url = data.url;
    if (data.systemId !== undefined) this.systemId = data.systemId;
    if (data.createdAt !== undefined) this.createdAt = data.createdAt;
    if (data.updatedAt !== undefined) this.updatedAt = data.updatedAt;
    if (data.deletedAt !== undefined) this.deletedAt = data.deletedAt;
  }
}

Object.defineProperty(ShortLink.prototype, "schema", {
  value: {
    $schema: "http://json-schema.org/draft-07/schema",
    $id: "shortLink.json",
    title: "Short Link",
    type: "object",
    required: ["destination", "url"],
    properties: {
      id: { $ref: "definitions.json#/definitions/id" },
      type: { type: "string", default: "shortLink", enum: ["shortLink"] },
      title: { type: "string" },
      destination: { type: "string", format: "uri" },
      url: { type: "string", format: "uri" },
      systemId: { $ref: "definitions.json#/definitions/systemId" },
      createdAt: { $ref: "definitions.json#/definitions/date" },
      updatedAt: { $ref: "definitions.json#/definitions/date" },
      deletedAt: { $ref: "definitions.json#/definitions/date" },
    },
  },
});

Object.defineProperty(ShortLink.prototype, "validator", {
  get: function () {
    return validate;
  },
});
