// This file is automatically generated. Do not modify it manually.

  import { Entity } from './entity';
  import { validateSwitch as validate } from '../validators/switch';

  export class Switch extends Entity {
	constructor(data) {
	  super(data);
	  this.id = data.id;
            this.name = data.name;
            this.type = data.type;
            this.discriminator = data.discriminator;
            this.supportedNotifications = data.supportedNotifications;
            this.notification = data.notification;
            this.driver = data.driver;
            this.offline = data.offline;
            this.state = data.state;
            this.systemId = data.systemId;
            this.watts = data.watts;
	}
	  

	
	  
	  

	  

	  
  }

  Object.defineProperty(Switch.prototype, "schema", {
	value: {"$schema":"http://json-schema.org/draft-07/schema","$id":"switch.json","title":"Switch","description":"Any smart switch","type":"object","properties":{"id":{"$ref":"definitions.json#/definitions/id"},"name":{"type":"string"},"type":{"$ref":"definitions.json#/definitions/type"},"discriminator":{"type":"string","enum":["light","fan","irrigation"]},"supportedNotifications":{"$ref":"definitions.json#/definitions/supportedNotifications"},"notification":{"$ref":"definitions.json#/definitions/notification"},"driver":{"$ref":"definitions.json#/definitions/driver"},"offline":{"type":"boolean"},"state":{"type":"string","enum":["on","off"]},"systemId":{"$ref":"definitions.json#/definitions/systemId"},"watts":{"$ref":"definitions.json#/definitions/watts"}},"required":["id","type","state","driver"]}
  });

  Object.defineProperty(Switch.prototype, "validator", {
	get: function() { return validate; }
  });
