// This file is automatically generated. Do not modify it manually.

  import { Entity } from './entity';
  import { validate } from '../validators/systemUser';

  export class SystemUser extends Entity {
	constructor(data) {
	  super(data);
	  this.id = data.id;
            this.type = data.type;
            this.driver = data.driver;
            this.firstName = data.firstName;
            this.lastName = data.lastName;
            this.phone = data.phone;
            this.email = data.email;
            this.address = data.address;
            this.photo = data.photo;
            this.jobTitle = data.jobTitle;
            this.dob = data.dob;
            this.gender = data.gender;
            this.roles = data.roles;
            this.nationality = data.nationality;
            this.notes = data.notes;
            this.files = data.files;
            this.identifications = data.identifications;
            this.payments = data.payments;
            this.revenue = data.revenue;
            this.createdAt = data.createdAt;
            this.updatedAt = data.updatedAt;
            this.systemId = data.systemId;
	}
	  

	
	  
	  

	  

	  
  }

  Object.defineProperty(SystemUser.prototype, "schema", {
	value: {"$schema":"http://json-schema.org/draft-07/schema","$id":"systemUser.json","title":"System User","description":"A system user is a user that originated from an external 3rd party system.","type":"object","required":["firstName","lastName"],"properties":{"id":{"$ref":"definitions.json#/definitions/id"},"type":{"type":"string","default":"systemUser","enum":["systemUser"]},"driver":{"$ref":"definitions.json#/definitions/driver"},"firstName":{"type":"string"},"lastName":{"type":"string"},"phone":{"type":["string","null"],"pattern":"^\\+[0-9]{1,14}$"},"email":{"type":["string","null"],"format":"email"},"address":{"$ref":"definitions.json#/definitions/address"},"photo":{"type":"string"},"jobTitle":{"type":"string"},"dob":{"type":"string"},"gender":{"type":"string","enum":["male","female"]},"roles":{"type":"array","items":{"type":"string","enum":["Guest","User","Manager","Maintenance","Administrator","SuperAdmin"]}},"nationality":{"type":"string","minLength":2,"maxLength":2},"notes":{"type":"array","items":{"type":"string"}},"files":{"type":"array","items":{"$ref":"mediaFile.json#"}},"identifications":{"type":"array","items":{"$ref":"identification.json#"}},"payments":{"type":"array","items":{"$ref":"payment.json#"}},"revenue":{"$ref":"definitions.json#/definitions/revenue"},"createdAt":{"$ref":"definitions.json#/definitions/createdAt"},"updatedAt":{"$ref":"definitions.json#/definitions/updatedAt"},"systemId":{"$ref":"definitions.json#/definitions/systemId"}}}
  });

  Object.defineProperty(SystemUser.prototype, "validator", {
	get: function() { return validate; }
  });
