// This file is automatically generated. Do not modify it manually.

  import { Entity } from './entity';
  import { validate } from '../validators/vendor';

  export class Vendor extends Entity {
	constructor(data) {
	  super(data);
	  this.id = data.id;
            this.type = data.type;
            this.name = data.name;
            this.phone = data.phone;
            this.email = data.email;
            this.address = data.address;
            this.photo = data.photo;
            this.createdAt = data.createdAt;
            this.updatedAt = data.updatedAt;
	}
	  

	
	  
	  

	  

	  
  }

  Object.defineProperty(Vendor.prototype, "schema", {
	value: {"$schema":"http://json-schema.org/draft-07/schema","$id":"vendor.json","title":"Vendor","type":"object","required":["name","email"],"properties":{"id":{"$ref":"definitions.json#/definitions/id"},"type":{"type":"string","default":"vendor","enum":["vendor"]},"name":{"type":"string"},"phone":{"type":["string","null"],"pattern":"^\\+[0-9]{1,14}$"},"email":{"type":["string","null"],"format":"email"},"address":{"$ref":"definitions.json#/definitions/address"},"photo":{"$ref":"mediaFile.json#"},"createdAt":{"$ref":"definitions.json#/definitions/createdAt"},"updatedAt":{"$ref":"definitions.json#/definitions/updatedAt"}}}
  });

  Object.defineProperty(Vendor.prototype, "validator", {
	get: function() { return validate; }
  });
