name: njsscan
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: Node JS Scan Check
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: "."
