# Sync Use Cases
---
name: Sync Use Cases

on:
  repository_dispatch:
    types: [sync-use-cases]

permissions:
  id-token: write
  contents: write

jobs:
  sync:
    name: Fetch Use Cases and Create PR
    runs-on: ubuntu-latest
    if: github.event.client_payload.version
    env:
      VERSION: ${{ github.event.client_payload.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: use-cases

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::859856851493:role/GithubActionsRole
          role-session-name: actionsS3Upload
          aws-region: us-east-1

      - name: Download use cases
        run: aws s3 cp s3://cloud-v3-data/useCases/useCases-${{ env.VERSION }}.json ./src/useCases/http.json

      - run: git config user.email github-actions@github.com
      - run: git config user.name github-actions
      - run: git add src/useCases/http.json
      - run: git commit -am "Update use cases to API version ${{ env.VERSION }}"
      - run: git push

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          base: "master"
          commit-message: "Update use cases to API version ${{ env.VERSION }}"
          title: "[CI] Update use cases to API version ${{ env.VERSION }}"
          body: "Update use cases to API version ${{ env.VERSION }}"
          branch: "use-cases"
          labels: "use-cases"
