# Sync Use Cases
---
name: Sync Use Cases

on:
  repository_dispatch:
    types: [sync-use-cases]

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    name: Save use cases to http.json
    runs-on: ubuntu-latest
    if: github.event.client_payload.hash
    env:
      HASH: ${{ github.event.client_payload.hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: use-cases

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::859856851493:role/GithubActionsRole
          role-session-name: actionsS3Upload
          aws-region: us-east-1

      - name: Download use cases
        run: aws s3 cp s3://cloud-v3-data/useCases/useCases-${{ env.hash }}.json ./src/useCases/http.json

      - run: git commit -am "Update use cases to hash ${{ env.hash }}"
      - run: git push

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update use cases to hash ${{ env.hash }}"
          title: "[CI] Update use cases to hash ${{ env.hash }}"
          body: "Update use cases to hash ${{ env.hash }}"
          branch: "use-cases"
          labels: "use-cases"
